usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /usuarios/

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

mirestaurante:
    resource: "@MirestauranteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
